### ISSUE TITLE
[FEATURE] Unicode support, api configuration

### ISSUE THREAD

**Issue by kopp4** [justchokingaround/jerry#8] opened 2023-02-19 12:54 UTC
I have no clue if this is my problem or not but, jerry seems to not support unicode either in fzf or rofi ? 
![image](https://user-images.githubusercontent.com/74755703/219949134-ee9a2d77-ff70-4ecd-adc2-445d3a15b8d9.png)
> Sorry for bothering.

**Comment by justchokingaround** [comment] 2023-02-19 13:09
how can i reproduce this bug?

**Comment by kopp4** [comment] 2023-02-19 15:01
I entered my api and here are my config dont know if it help
```
use_external_menu=1
discord_presence="true"
# provider="gogoanime"
provider="9anime"
opt_fzf_args="--cycle --reverse"
# subs_language="japanese"
subs_language="english"
video_quality=best
```

And I entered 
```
jerry -c
```

**Comment by justchokingaround** [comment] 2023-02-19 15:02
could you give me the anime names pls?

**Comment by justchokingaround** [comment] 2023-02-19 15:02
(i don't scrape 9anime btw, so it will fallback to gogoanime)

**Comment by kopp4** [comment] 2023-02-19 15:04
![image](https://user-images.githubusercontent.com/74755703/219956372-3d24ca21-06ef-4349-bca9-efce21a2a0c6.png)

Do I  post my anilist profile link here?

**Comment by justchokingaround** [comment] 2023-02-19 15:10
```sh
curl -s -X POST "https://graphql.anilist.co" \
                -H 'Content-Type: application/json' \
                -H "Authorization: Bearer $(cat ~/.cache/jerry/anilist_token.txt)" \
                -d "{\"query\":\"query(\$userId:Int,\$userName:String,\$type:MediaType){MediaListCollection(userId:\$userId,userName:\$userName,type:\$type){lists{name isCustomList isCompletedList:isSplitCompletedList entries{...mediaListEntry}}user{id name avatar{large}mediaListOptions{scoreFormat rowOrder animeList{sectionOrder customLists splitCompletedSectionByFormat theme}mangaList{sectionOrder customLists splitCompletedSectionByFormat theme}}}}}fragment mediaListEntry on MediaList{id mediaId status score progress progressVolumes repeat priority private hiddenFromStatusLists customLists advancedScores notes updatedAt startedAt{year month day}completedAt{year month day}media{id title{userPreferred romaji english native}coverImage{extraLarge large}type format status(version:2)episodes volumes chapters averageScore popularity isAdult countryOfOrigin genres bannerImage startDate{year month day}}}\",\"variables\":{\"userId\":$(cat ~/.cache/jerry/anilist_user_id.txt),\"type\":\"ANIME\"}}" | tr "\[|\]" "\n" | grep CURRENT > list.txt
 ```
 
 can you please run this, and then send me the list.txt file?

**Comment by kopp4** [comment] 2023-02-19 15:13
Here is the [list.txt](https://github.com/justchokingaround/jerry/files/10777193/list.txt)

**Comment by justchokingaround** [comment] 2023-02-19 15:16
ok i see the problem now, it's because i'm using `userPreferred` instead of `english` for extracting the title. you could try making a pr to fix it, or i'll push a fix tonight when i come back home

**Comment by kopp4** [comment] 2023-02-19 15:26
I personally don't really understand English title sorry, would you be so kind as to tell me if it's possible to support unicode?

**Comment by justchokingaround** [comment] 2023-02-19 15:28
oh ok, np. i will have to look into it, i remember running into that problem a while ago, and didn't find a solution. i will find one this time dw :+1: (might take some time)

**Comment by justchokingaround** [comment] 2023-02-19 19:10
@kopp4 
this commit to the `unicode-characters`: https://github.com/justchokingaround/jerry/commit/e836f8c494d6da78d5854a7d5499910fc58bb025  branch should fix this bug, could you test it out please? if you need help with how to set it up and test i will help np, just ask me

here is my result after i tested locally:
![image](https://user-images.githubusercontent.com/44473782/219969797-a82ce1bf-2a2d-4d52-8503-73a829656304.png)
![image](https://user-images.githubusercontent.com/44473782/219969822-de2e674b-322a-4bcc-bc95-16d0089b4e16.png)

**Comment by kopp4** [comment] 2023-02-19 23:24
Yes, it's working perfectly, thank you!
![image](https://user-images.githubusercontent.com/74755703/219981693-a1ee103d-dc3d-4903-81d1-edea86330b81.png)

**Comment by justchokingaround** [comment] 2023-02-19 23:54
https://user-images.githubusercontent.com/44473782/219983062-2c960c3b-c236-4f68-86dd-7dd7ed4fbe17.mp4

you probably just got unlucky timing and zoro changed their encryption keys i guess, because the anime title doesn't affect the search process, only the media id is used

**Comment by justchokingaround** [comment] 2023-02-19 23:54
this is from the `feat-manga` branch

**Comment by kopp4** [comment] 2023-02-20 00:49
> you probably just got unlucky timing and zoro changed their encryption keys i guess, because the anime title doesn't affect the search process, only the media id is used

The file is corrupted..

**Comment by justchokingaround** [comment] 2023-02-20 01:08
it's only corrupted on phone, you have to download it to be able to see it. i don't know exactly why this happens, i will try to figure it out some day. on a computer it plays fine as well

**Comment by kopp4** [comment] 2023-02-20 01:54
![image](https://user-images.githubusercontent.com/74755703/219991423-0b2ba3f1-9470-42d0-9863-2f0a53a524a9.png)

**Comment by justchokingaround** [comment] 2023-02-20 02:06
PLEASE CHECK THAT THE FILE YOU SHARE DOES NOT CONTAIN YOUR ANILIST TOKEN
could you please run these 2 commands so i can see some logs for what's happening?
```sh
sh -x jerry.sh -c 2> idk.log
echo "$(tail -50 idk.log)" > idk.log
```
PLEASE CHECK THAT THE FILE YOU SHARE DOES NOT CONTAIN YOUR ANILIST TOKEN

**Comment by kopp4** [comment] 2023-02-20 02:35
Here is [idk.log](https://github.com/justchokingaround/jerry/files/10778934/idk.log)

**Comment by justchokingaround** [comment] 2023-02-20 02:37
i need to see the last request being made, could you increase the value for the tail please? still make sure to not accidentally share your token

**Comment by kopp4** [comment] 2023-02-20 02:39
Like this [idk.log](https://github.com/justchokingaround/jerry/files/10778952/idk.log) ?

**Comment by justchokingaround** [comment] 2023-02-20 02:41
need just a little bit more. i'm not sure where it starts to break
![image](https://user-images.githubusercontent.com/44473782/219997287-4255c714-bd4b-4479-a174-37a2a6e28a17.png)

**Comment by justchokingaround** [comment] 2023-02-20 02:43
this part, where the `media_id` is first parsed, also interests me, if you could find it :point_right: :point_left: 
![image](https://user-images.githubusercontent.com/44473782/219997475-c2b37dde-9cef-4598-a2ee-fbc6a3e4440b.png)

**Comment by kopp4** [comment] 2023-02-20 02:45
![image](https://user-images.githubusercontent.com/74755703/219997594-4b578364-59d1-4db7-8350-7ae9772ff61a.png)

**Comment by justchokingaround** [comment] 2023-02-20 02:46
oh interesting

**Comment by kopp4** [comment] 2023-02-20 02:47
> oh interesting

What that was actually useful?! I just ditched it
![image](https://user-images.githubusercontent.com/74755703/219997953-3324a29e-1259-4ba8-b901-651a5b422a66.png)

**Comment by kopp4** [comment] 2023-02-20 02:50
Oh it's working now!!!!!!

**Comment by justchokingaround** [comment] 2023-02-20 02:50
perfect. in that case i will add an option for the configuration file to use a flexible url for the api host :+1:

**Comment by kopp4** [comment] 2023-02-20 02:51
Thanks a lot bro, really mean it, case closed?

**Comment by justchokingaround** [comment] 2023-02-20 02:53
i will close this issue when i merge `feat-manga` :+1:

**Comment by justchokingaround** [comment] 2023-02-20 15:28
> perfect. in that case i will add an option for the configuration file to use a flexible url for the api host :+1:

done in https://github.com/justchokingaround/jerry/commit/357117754d79ab1267205d4e4aed7947c39abea3

**Closed** 2023-06-27 11:12 UTC
